### PR TITLE
Add test support for Heroku CI

### PR DESCRIPTION
**Pull request by markshiz**

### CODE REVIEW

**Comment by vzsg** [comment]
Hi!

Thanks for the PR, looks like an interesting improvement. There's one thing I noticed: the `test` script should not be Vapor-specific, as this buildpack aims to support any Swift project. Could you replace that with a hook invocation instead?

**Comment by markshiz** [comment]
@vzsg Sort of a naive question, but is there a preferred way to detect that this is a vapor app --e.g., by inspecting the app payload?  I don't see any scripts written for that yet.

**Comment by vzsg** [comment]
Well, there's no clean way to do that, and even if there was, not all Vapor projects are equal — the more self-sustained ones won't need a manual `migrate` call before the tests are run, for example.

Which is why I suggested copying the pre_compile/post_compile hooks, so the projects that use this buildpack can add whatever customization they need.

**Comment by markshiz** [comment]
@vzsg This seems to be working for me now.

**Pull request merged**
